# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('slug', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ImageField(upload_to='post/post_picture')),
                ('text', models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442')),
                ('display', models.BooleanField(default=True)),
                ('like', models.IntegerField()),
                ('dislike', models.IntegerField()),
            ],
        ),
    ]
