# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 12:52
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20160711_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=redactor.fields.RedactorField(verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
    ]
