# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20160718_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.CharField(blank=True, max_length=45, null=True, unique=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(blank=True, max_length=45, null=True, unique=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430'),
        ),
    ]
